export const USER_SEARCH_SUGGESTED_REQUEST = "USER_SEARCH_SUGGESTED_REQUEST"
export const USER_SEARCH_SUGGESTED_SUCCESS = "USER_SEARCH_SUGGESTED_SUCCESS"
export const USER_SEARCH_SUGGESTED_FAILURE = "USER_SEARCH_SUGGESTED_FAILURE"

export const FETCH_SEARCH_DATA_REQUEST = "FETCH_SEARCH_DATA_REQUEST"
export const FETCH_SEARCH_DATA_SUCCESS = "FETCH_SEARCH_DATA_SUCCESS"
export const FETCH_SEARCH_DATA_FAILURE = "FETCH_SEARCH_DATA_FAILURE"