export const FETCH_ADMIN_COUNT_REQUEST = "FETCH_ADMIN_COUNT_REQUEST"
export const FETCH_ADMIN_COUNT_SUCCESS = "FETCH_ADMIN_COUNT_SUCCESS"
export const FETCH_ADMIN_COUNT_FAILURE = "FETCH_ADMIN_COUNT_FAILURE"