export const STORE_FETCH_PRODUCTS_BASES_REQUEST = "STORE_FETCH_PRODUCTS_BASES_REQUEST";
export const STORE_FETCH_PRODUCTS_BASES_SUCCESS = "STORE_FETCH_PRODUCTS_BASES_SUCCESS";
export const STORE_FETCH_PRODUCTS_BASES_FAILURE = "STORE_FETCH_PRODUCTS_BASES_FAILURE";

export const STORE_FETCH_BRANDS_REQUEST = 'STORE_FETCH_BRANDS_REQUEST';
export const STORE_FETCH_BRANDS_SUCCESS = 'STORE_FETCH_BRANDS_SUCCESS';
export const STORE_FETCH_BRANDS_FAILURE = 'STORE_FETCH_BRANDS_FAILURE';

export const STORE_FETCH_CATEGORIES_REQUEST = 'STORE_FETCH_CATEGORIES_REQUEST';
export const STORE_FETCH_CATEGORIES_SUCCESS = 'STORE_FETCH_CATEGORIES_SUCCESS';
export const STORE_FETCH_CATEGORIES_FAILURE = 'STORE_FETCH_CATEGORIES_FAILURE';

export const STORE_INSERT_PRODUCT_REQUEST = "STORE_INSERT_PRODUCT_REQUEST"
export const STORE_INSERT_PRODUCT_SUCCESS = "STORE_INSERT_PRODUCT_SUCCESS"
export const STORE_INSERT_PRODUCT_FAILURE = "STORE_INSERT_PRODUCT_FAILURE"

export const FETCH_STORE_COUNT_REQUEST = "FETCH_STORE_COUNT_REQUEST"
export const FETCH_STORE_COUNT_SUCCESS = "FETCH_STORE_COUNT_SUCCESS"
export const FETCH_STORE_COUNT_FAILURE = "FETCH_STORE_COUNT_FAILURE"

export const STORE_CHANGE_PASSWORD_REQUEST = "STORE_CHANGE_PASSWORD_REQUEST" 
export const STORE_CHANGE_PASSWORD_SUCCESS = "STORE_CHANGE_PASSWORD_SUCCESS" 
export const STORE_CHANGE_PASSWORD_FAILURE = "STORE_CHANGE_PASSWORD_FAILURE"