export const STORE_FETCH_FACTORES_REQUEST = "STORE_FETCH_FACTORES_REQUEST";
export const STORE_FETCH_FACTORES_SUCCESS = "STORE_FETCH_FACTORES_SUCCESS";
export const STORE_FETCH_FACTORES_FAILURE = "STORE_FETCH_FACTORES_FAILURE";

export const STORE_FETCH_INVOICE_ITEMS_REQUEST = "STORE_FETCH_INVOICE_ITEMS_REQUEST";
export const STORE_FETCH_INVOICE_ITEMS_SUCCESS = "STORE_FETCH_INVOICE_ITEMS_SUCCESS";
export const STORE_FETCH_INVOICE_ITEMS_FAILURE = "STORE_FETCH_INVOICE_ITEMS_FAILURE";

export const  STORE_ACTION_LOADING_REQUEST = "STORE_ACTION_LOADING_REQUEST";
export const  STORE_ACTION_LOADING_SUCCESS = "STORE_ACTION_LOADING_SUCCESS";
export const  STORE_ACTION_LOADING_FAILURE = "STORE_ACTION_LOADING_FAILURE";