export const FETCH_STORE_REQUEST = "FETCH_STORE_REQUEST" 
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS"
export const FETCH_STORE_FAILURE = "FETCH_STORE_FAILURE"
export const REMOVE_STORE_DATA = "REMOVE_STORE_DATA"
