export const ADMIN_FETCH_BRANDS_REQUEST = "ADMIN_FETCH_BRANDS_REQUEST"
export const ADMIN_FETCH_BRANDS_SUCCESS = "ADMIN_FETCH_BRANDS_SUCCESS"
export const ADMIN_FETCH_BRANDS_FAILURE = "ADMIN_FETCH_BRANDS_FAILURE"