export const ADMIN_FETCH_PRODUCTS_REQUEST = 'ADMIN_FETCH_PRODUCTS_REQUEST'
export const ADMIN_FETCH_PRODUCTS_SUCCESS = 'ADMIN_FETCH_PRODUCTS_SUCCESS'
export const ADMIN_FETCH_PRODUCTS_FAILURE = 'ADMIN_FETCH_PRODUCTS_FAILURE'

export const ADMIN_FETCH_ONE_PRODUCT_REQUEST = 'ADMIN_FETCH_ONE_PRODUCT_REQUEST'
export const ADMIN_FETCH_ONE_PRODUCT_SUCCESS = 'ADMIN_FETCH_ONE_PRODUCT_SUCCESS'
export const ADMIN_FETCH_ONE_PRODUCT_FAILURE = 'ADMIN_FETCH_ONE_PRODUCT_FAILURE'

export const ADMIN_INSERT_ONE_PRODUCT_REQUEST = 'ADMIN_INSERT_ONE_PRODUCT_REQUEST'
export const ADMIN_INSERT_ONE_PRODUCT_SUCCESS = 'ADMIN_INSERT_ONE_PRODUCT_SUCCESS'
export const ADMIN_INSERT_ONE_PRODUCT_FAILURE = 'ADMIN_INSERT_ONE_PRODUCT_FAILURE'

export const ADMIN_FETCH_SUB_1_REQUEST = 'ADMIN_FETCH_SUB_1_REQUEST'
export const ADMIN_FETCH_SUB_1_SUCCESS = 'ADMIN_FETCH_SUB_1_SUCCESS'
export const ADMIN_FETCH_SUB_1_FAILURE = 'ADMIN_FETCH_SUB_1_FAILURE'

export const ADMIN_FETCH_SUB_2_REQUEST = 'ADMIN_FETCH_SUB_2_REQUEST'
export const ADMIN_FETCH_SUB_2_SUCCESS = 'ADMIN_FETCH_SUB_2_SUCCESS'
export const ADMIN_FETCH_SUB_2_FAILURE = 'ADMIN_FETCH_SUB_2_FAILURE'

export const ADMIN_FETCH_SUB_3_REQUEST = 'ADMIN_FETCH_SUB_3_REQUEST'
export const ADMIN_FETCH_SUB_3_SUCCESS = 'ADMIN_FETCH_SUB_3_SUCCESS'
export const ADMIN_FETCH_SUB_3_FAILURE = 'ADMIN_FETCH_SUB_3_FAILURE'

export const ADMIN_FETCH_BRANDS_REQUEST = 'ADMIN_FETCH_BRANDS_REQUEST'
export const ADMIN_FETCH_BRANDS_SUCCESS = 'ADMIN_FETCH_BRANDS_SUCCESS'
export const ADMIN_FETCH_BRANDS_FAILURE = 'ADMIN_FETCH_BRANDS_FAILURE'

export const ADMIN_FETCH_CATEGORIES_REQUEST = 'ADMIN_FETCH_CATEGORIES_REQUEST'
export const ADMIN_FETCH_CATEGORIES_SUCCESS = 'ADMIN_FETCH_CATEGORIES_SUCCESS'
export const ADMIN_FETCH_CATEGORIES_FAILURE = 'ADMIN_FETCH_CATEGORIES_FAILURE'