export const FETCH_LIKES_REQUEST = "FETCH_LIKES_REQUEST"
export const FETCH_LIKES_SUCCESS = "FETCH_LIKES_SUCCESS"
export const FETCH_LIKES_FAILURE = "FETCH_LIKES_FAILURE"
export const INSERT_LIKE_LOADING = "INSERT_LIKE_LOADING"

