export const CART_ADD_TO_CART_REQUEST =  "CART_ADD_TO_CART_REQUEST"   
export const CART_ADD_TO_CART_SUCCESS =  "CART_ADD_TO_CART_SUCCESS"   
export const CART_ADD_TO_CART_FAILURE =  "CART_ADD_TO_CART_FAILURE"   

// Loading - Add to Cart 
export const CART_ADD_TO_CART_LOADING_REQUEST = "CART_ADD_TO_CART_LOADING_REQUEST"
export const CART_ADD_TO_CART_LOADING_SUCCESS = "CART_ADD_TO_CART_LOADING_SUCCESS"
export const CART_ADD_TO_CART_LOADING_FAILURE = "CART_ADD_TO_CART_LOADING_FAILURE"

// Loading - Increase Or Decrese Product 
export const CART_INCREASE_OR_DECREASE_PRODUCT_LOADING_REQUEST = "CART_INCREASE_OR_DECREASE_PRODUCT_LOADING_REQUEST"
export const CART_INCREASE_OR_DECREASE_PRODUCT_LOADING_SUCCESS = "CART_INCREASE_OR_DECREASE_PRODUCT_LOADING_SUCCESS"
export const CART_INCREASE_OR_DECREASE_PRODUCT_LOADING_FAILURE = "CART_INCREASE_OR_DECREASE_PRODUCT_LOADING_FAILURE"

export const FETCH_MAIN_CART_REQUEST = "FETCH_MAIN_CART_REQUEST"
export const FETCH_MAIN_CART_SUCCESS = "FETCH_MAIN_CART_SUCCESS"
export const FETCH_MAIN_CART_FAILURE = "FETCH_MAIN_CART_FAILURE"