export const ADMIN_FETCH_CATEGORIES_REQUEST = "ADMIN_FETCH_CATEGORIES_REQUEST"
export const ADMIN_FETCH_CATEGORIES_SUCCESS = "ADMIN_FETCH_CATEGORIES_SUCCESS"
export const ADMIN_FETCH_CATEGORIES_FAILUE = "ADMIN_FETCH_CATEGORIES_FAILUE"

export const ADMIN_INSERT_CATEGORIES_REQUEST = "ADMIN_INSERT_CATEGORIES_REQUEST"
export const ADMIN_INSERT_CATEGORIES_SUCCESS = "ADMIN_INSERT_CATEGORIES_SUCCESS"
export const ADMIN_INSERT_CATEGORIES_FAILUE = "ADMIN_INSERT_CATEGORIES_FAILUE"