export const STORE_FETCH_PRODUCTS_BASES_REQUEST = "STORE_FETCH_PRODUCTS_BASES_REQUEST";
export const STORE_FETCH_PRODUCTS_BASES_SUCCESS = "STORE_FETCH_PRODUCTS_BASES_SUCCESS";
export const STORE_FETCH_PRODUCTS_BASES_FAILURE = "STORE_FETCH_PRODUCTS_BASES_FAILURE";

export const STORE_FETCH_BRANDS_REQUEST = 'STORE_FETCH_BRANDS_REQUEST';
export const STORE_FETCH_BRANDS_SUCCESS = 'STORE_FETCH_BRANDS_SUCCESS';
export const STORE_FETCH_BRANDS_FAILURE = 'STORE_FETCH_BRANDS_FAILURE';

export const STORE_FETCH_CATEGORIES_REQUEST = 'STORE_FETCH_CATEGORIES_REQUEST';
export const STORE_FETCH_CATEGORIES_SUCCESS = 'STORE_FETCH_CATEGORIES_SUCCESS';
export const STORE_FETCH_CATEGORIES_FAILURE = 'STORE_FETCH_CATEGORIES_FAILURE';

export const STORE_INSERT_PRODUCT_REQUEST = "STORE_INSERT_PRODUCT_REQUEST"
export const STORE_INSERT_PRODUCT_SUCCESS = "STORE_INSERT_PRODUCT_SUCCESS"
export const STORE_INSERT_PRODUCT_FAILURE = "STORE_INSERT_PRODUCT_FAILURE"