export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE"

export const SIGNIN_USER_REQUEST = "SIGNUP_USER_REQUEST"
export const SIGNIN_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const SIGNIN_USER_FAILURE = "SIGNUP_USER_FAILURE"

export const AUTH_PANEL = "AUTH_PANEL"