export const ADMIN_INSERT_STORE_REQUEST = "ADMIN_INSERT_STORE_REQUEST"
export const ADMIN_INSERT_STORE_SUCCESS = "ADMIN_INSERT_STORE_SUCCESS"
export const ADMIN_INSERT_STORE_FAILURE = "ADMIN_INSERT_STORE_FAILURE"

export const ADMIN_FETCH_STORE_REQUEST = "ADMIN_FETCH_STORE_REQUEST"
export const ADMIN_FETCH_STORE_SUCCESS = "ADMIN_FETCH_STORE_SUCCESS"
export const ADMIN_FETCH_STORE_FAILURE = "ADMIN_FETCH_STORE_FAILURE"

export const ADMIN_FETCH_ONE_STORE_REQUEST = "ADMIN_FETCH_ON_STORE_REQUEST"
export const ADMIN_FETCH_ONE_STORE_SUCCESS = "ADMIN_FETCH_ON_STORE_SUCCESS"
export const ADMIN_FETCH_ONE_STORE_FAILURE = "ADMIN_FETCH_ON_STORE_FAILURE"