export const ADMIN_INSERT_USER_REQUEST = "ADMIN_INSERT_USER_REQUEST"
export const ADMIN_INSERT_USER_SUCCESS = "ADMIN_INSERT_USER_SUCCESS"
export const ADMIN_INSERT_USER_FAILURE = "ADMIN_INSERT_USER_FAILURE"

export const ADMIN_FETCH_USERS_REQUEST = "ADMIN_FETCH_USERS_REQUEST"
export const ADMIN_FETCH_USERS_SUCCESS = "ADMIN_FETCH_USERS_SUCCESS"
export const ADMIN_FETCH_USERS_FAILURE = "ADMIN_FETCH_USERS_FAILURE"

export const ADMIN_FETCH_ONE_USER_REQUEST = "ADMIN_FETCH_ONE_USER_REQUEST"
export const ADMIN_FETCH_ONE_USER_SUCCESS = "ADMIN_FETCH_ONE_USER_SUCCESS"
export const ADMIN_FETCH_ONE_USER_FAILURE = "ADMIN_FETCH_ONE_USER_FAILURE"