export const USER_FETCH_INVOICES_REQUEST = "USER_FETCH_INVOICES_REQUEST"
export const USER_FETCH_INVOICES_SUCCESS = "USER_FETCH_INVOICES_SUCCESS"
export const USER_FETCH_INVOICES_FAILURE = "USER_FETCH_INVOICES_FAILURE"

export const  USER_ACTION_LOADING_REQUEST = "USER_ACTION_LOADING_REQUEST";
export const  USER_ACTION_LOADING_SUCCESS = "USER_ACTION_LOADING_SUCCESS";
export const  USER_ACTION_LOADING_FAILURE = "USER_ACTION_LOADING_FAILURE";